version: '3'
services:
  puppetserver:
    build:
      dockerfile: Dockerfile.source
      context: puppetserver
    hostname: puppet.docker
    ports:
      - 8140:8140
    volumes:
      - ./ssl:/etc/puppetlabs/puppet/ssl
      - ./puppet.conf:/etc/puppetlabs/puppet/puppet.conf
      - ./puppet:/puppet
      - ./hiera:/hiera
      - ./facter:/facter
      - ./code:/etc/puppetlabs/code
  vault:
    image: vault
    hostname: vault.docker
    volumes:
      - ./ssl/certs/ca.pem:/vault/config/ca.pem
      - ./ssl/certs/vault.docker.pem:/vault/config/cert.pem
      - ./ssl/private_keys/vault.docker.pem:/vault/config/private_key.pem
    ports:
      - 8200:8200
      - 8201:8201
    depends_on:
      - puppetserver
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_LOCAL_CONFIG: >
        {
          "backend": {
            "file": {
              "path": "/vault/file"
            }
          },
          "default_lease_ttl": "168h",
          "max_lease_ttl": "720h",
          "listener": {
            "tcp": {
              "address": "0.0.0.0:8200",
              "tls_cert_file": "/vault/config/cert.pem",
              "tls_key_file": "/vault/config/private_key.pem"
            }
          }
        }
      VAULT_ADDR: "https://vault.docker:8200"
      VAULT_CACERT: "/vault/config/ca.pem"
      VAULT_CLIENT_KEY: "/vault/config/private_key.pem"
      VAULT_CLIENT_CERT: "vault/config/cert.pem"
    command: ["server"]
  agent:
    build:
      dockerfile: ../docker/puppet/Dockerfile
      context: puppet
    hostname: agent.docker
    command: ["tail", "-f", "/dev/null"]
    links:
      - puppetserver:puppet
      - vault:vault.docker
    volumes:
      - ./ssl:/etc/puppetlabs/puppet/ssl
